import "./globals.scss";
import '@fortawesome/fontawesome-free/css/all.min.css';


export const metadata = {
  title: "Dhairya Bhardwaj",
  description: "Generated by yaml2resume",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-serif flex justify-center items-center min-h-screen antialiased print:bg-white'>
        <div class="flex flex-col h-screen">
          <header class="h-8 bg-blue-600 w-screen text-white flex items-center justify-center shadow-md">
            Top Menu Bar
          </header>
          <main class="flex-1 overflow-y-auto w-screen bg-gray-500">
              {children}
          </main>
          <footer class="h-8 bg-gray-100 w-screen text-white flex items-center justify-center shadow-md">
            Status Bar
          </footer>
        </div>
      </body>
    </html>
  );
}
