import "./globals.scss";
import '@fortawesome/fontawesome-free/css/all.min.css';


export const metadata = {
  title: "Yaml2cv",
  description: "Generated by yaml2cv",
};

export default function Layout({ children, header }) {
  return (
    <html lang="en">
      <body className='font-serif flex flex-col h-screen justify-center items-center antialiased print:bg-white print:h-full print:contents'>
        <div className="h-8 p-2 bg-blue-50 font-thin text-yellow-900 w-screen gap-8 leading-tight flex items-center justify-center shadow-md print:hidden">
          {header}
        </div>
        <div className="min-h-0 flex-1 w-screen bg-gray-500 grid place-items-center items-center justify-center print:contents">
          {children}
        </div>
      </body>
    </html>
  );
}
