import "./globals.scss";
import '@fortawesome/fontawesome-free/css/all.min.css';


export const metadata = {
  title: "Dhairya Bhardwaj",
  description: "Generated by yaml2resume",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-serif flex flex-col h-screen justify-center items-center antialiased print:bg-white print:h-full print:contents'>
          <header className="h-8 bg-blue-600 w-screen text-white flex items-center justify-center shadow-md print:hidden">
            Top Menu Bar
          </header>
          <main className="flex-1 overflow-y-auto w-screen h-full flex justify-center items-center bg-gray-500 print:contents">
              {children}
          </main>
      </body>
    </html>
  );
}
